### PR TITLE
Update required IAM policies for ElasticBeanstalk

### PR DESCRIPTION
**Pull request by mlocher**

### CODE REVIEW

**Comment by mlocher** [comment]
Good idea, how I love JSON :)

**Comment by sdbondi** [comment]
Cool - I've tested this and it works great! :+1:

**Comment by sdbondi** [comment]
IAM permissions will drive you crazy! :weary: 
I needed to add the following permissions when running with more than one instance:

```json
 {
            "Effect": "Allow",
            "Action": [
                "elasticloadbalancing:DescribeInstanceHealth",
                "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
                "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
            ],
            "Resource": "*"
        }
```

**Comment by mlocher** [comment]
Pushed another update, see https://codeship.com/documentation/continuous-deployment/deployment-to-elastic-beanstalk/ :)

**Pull request merged**
