### PR TITLE
Remove outdated link in documentation

### PR DESCRIPTION
**Pull request by flomotlik**

### CODE REVIEW

**Comment by mlocher** [comment]
:shipit:

**Comment by bfosberry** [comment]
We actually forked this to codeship/go-encrypt

**Comment by flomotlik** [comment]
I'm not sure even then if we should keep that in the docs. Imho the advantage of having it there is rather low and we can keep the content more focused on features. @mlocher thoughts?

**Comment by mlocher** [comment]
I agree, if we add technical details on the `jet` CLI we can add a link to the fork, I don't think this is required at the moment.

**Comment by bfosberry** [comment]
:+1:

**Pull request merged**
