### PR TITLE
Publish Docker image

### PR DESCRIPTION
**Pull request by mlocher**
After switching the development workflow to Docker in #399, publish the Docker image built for development on the Docker Hub.

That will allow (external) developers to pull the image instead of having to build it locally.

### CODE REVIEW

**Comment by mlocher** [comment]
We need to merge #413 before merging this.

**Comment by nunopato** [comment]
LGTM I think :)

**Comment by rheinwein** [comment]
:shipit:

**Comment by mlocher** [comment]
Merci :)

**Pull request merged**
