### PR TITLE
Documentation better naming

### PR DESCRIPTION
**Pull request by nunopato**
Those are small improvements/fixes I'm finding while reading the documentation.

### CODE REVIEW

**Comment by mlocher** [comment]
:shipit:

**Comment by nunopato** [comment]
@mlocher thanks :) since I'm not entirely sure about the process yet, I have to ask, can I merge this already ?

**Comment by mlocher** [comment]
Yeah, just go ahead and merge the PR as well as delete the branch afterwards. I'll send you a link to the build on Slack as the URL isn't public 😄

**Comment by nunopato** [comment]
cool thanks

**Pull request merged**
