### PR TITLE
adding community images page

### PR DESCRIPTION
**Pull request by ethangj**

### CODE REVIEW

**Comment by mlocher** [comment]
Fixed the breaking `gulp` task, 
:shipit: from my pov

**Comment by mlocher** [comment]
One comment after looking at the changes again, do you think it would be better to link to the pages on Docker Hub instead of GitHub?

Basically link to https://hub.docker.com/r/huli/webdriverio/ in the documentation instead of https://github.com/hulilabs/webdriverio. The GitHub repository is linked from the Docker Hub page anyways.

**Comment by ethangj** [comment]
@mlocher Updated to Dockerhub images.

**Comment by mlocher** [comment]
:shipit: if the build is green

**Pull request merged**
