### PR TITLE
Build only on PR changes

### PR DESCRIPTION
**Pull request by dennisnewel**
This PR will include changes related to the Build only on PR feature

### CODE REVIEW

**Comment by ethangj** [comment]
@dennisnewel Fine as is, but what do you think or rewriting it into a "Build triggers" article - retitle, add all the options, skipping is just one section

**Comment by dennisnewel** [comment]
Yeah, should probably have a separate page. At this stage the PR was mainly used to show @petra-sargent around. We discovered that the regex option is behind the same feature flag as build only on PR, so we figured we'd put everything in here eventually

**Comment by ethangj** [comment]
Got it, I don’t even know if Id do a separate page but maybe just convert this into the build triggers page and include skipping as part of that.

**Comment by dennisnewel** [comment]
gotcha. makes sense

**Comment by petra-sargent** [comment]
I am closing this PR.  The documentation for Build only on PR is addressed in this PR: https://github.com/codeship/documentation/pull/1440

**Pull request closed without merging**
