### PR TITLE
Homepage changes

### PR DESCRIPTION
**Pull request by ethangj**

### CODE REVIEW

**Comment by mlocher** [comment]
@ethangj could you push this to a staging build so we can take a look? Thx.

**Comment by ethangj** [comment]
@mlocher https://documentation.codeship.com/staging/home/

**Comment by mlocher** [comment]
Thanks. 

What do you think about adding _Basic_ & _Pro_ to the top navigation again?

**Comment by ethangj** [comment]
@mlocher I'm a little wary of making the top nav bigger again, but I also think we should try it. Maybe we could ship this and thend discuss a way to "validate" top menu changes?

**Comment by mlocher** [comment]
> I'm a little wary of making the top nav bigger again, but I also think we should try it. Maybe we could ship this and thend discuss a way to "validate" top menu changes?

Yeah, works for me. This PR is already approved. Maybe we can run an A/B test with the top nav?

**Pull request merged**
